### PR TITLE
file commit

### PR DESCRIPTION
**Pull request by kuldeepbanga19**
Please review and confirm

### CODE REVIEW

**Review by justinhunt — CHANGES_REQUESTED** [review]
There are references to mod_assign in the classes/dates.php code.
Please remove these and replace them with any necessary code from minilesson

**Review by justinhunt — CHANGES_REQUESTED** [review]
Thanks Kuldeep. Can i request  few changes here:

Please add a lang string for the new capability:
$string['wordcards:preview'] = 'Can preview Wordcards activities';

In view.php you added calls to get moduleinstance(line 24) and modulecontext(line 36). Wordcards is coded a bit differently to the other modules. 
You can get an instance of moduleinstance with:
$mod->get_mod();
You can get an instance of modulecontext with:
$mod->get_context();
Please use those instead to keep it consistent and save on DB calls

**Review by kuldeepbanga19 — COMMENTED** [review]
Please review the changes

**Comment by kuldeepbanga19** [comment]
Please review

**Review by justinhunt — APPROVED** [review]
looks good

**Pull request merged**
